### ISSUE TITLE
Multiple versions of the doc

### ISSUE THREAD

**Issue by duboism** [ebi-pf-team/interproscan-docs#2]
Hello,

If I'm correct, there is only 1 version of the documentation on Read the Docs: `latest` which usually corresponds to the content of the `master` branch on GitHub at the time of compilation./

I think it would be nice to be able to access several versions of the documentation (1 for each release of `interproscan`). For instance, as we install `interproscan` on our machines, so we sometimes need to access the documentation of previous versions.

This is relatively easy to do with Read the Docs (IIRC).

**Comment by gsn7** [comment]
yes,there is currently only 1 version.  we will workout to have multiple versions

**Comment by duboism** [comment]
Good news. IIRC, [this page should help you](https://readthedocs.org/projects/microscope/versions/).

**Comment by gsn7** [comment]
this is now implemented

**Comment by duboism** [comment]
Good news, thanks !
